swagger: '2.0'
info:
  title: Homescreen Plugin API
  description: Every plugin is required to implement this API
  version: "v1"
host: localhost:3001
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /plugin/metadata:
    get:
      summary: Gets plugin metadate
      description: |
        This endpoint provides metadata, which is used by the core to display it to the admin.
      tags:
        - Metadata
      responses:
        200:
          description: An object which contains the metadata
          schema:
            $ref: '#/definitions/Metadata'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Metadata:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      name:
        type: string
        description: Description of product.
      version:
        type: string
        description: Display name of product.
      description:
        type: string
        description: Capacity of product. For example, 4 people.
  Error:
    type: object
    properties:
      message:
        type: string
        description: A human readable error message.
      error:
        type: string
        description: The error message generated by the system. Useful for debugging.
